### ISSUE TITLE
关于项目的论文

### ISSUE THREAD

**Issue by chengming1108** [JNhua/Chinese_NER_with_Attention#2]
您好 能告诉一下我这个项目的论文题目吗 我想学习一下

**Comment by JNhua** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        此为毕业设计论文，未发表。
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                hjntc59
                            
                    
                        
                            
                                    hjntc59@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年8月14日 10:48，chengming1108<notifications@github.com> 写道： 


您好 能告诉一下我这个项目的论文题目吗 我想学习一下



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by JNhua** [comment]
此为毕业设计论文，未发表

**Comment by JNhua** [comment]
> 您好 能告诉一下我这个项目的论文题目吗 我想学习一下

此为毕业设计论文，未发表

**Comment by chengming1108** [comment]
我想跟您请教一下，这att模型是不是soft-attention模型。我没太懂att层中最后一句self.new_output = tf.concat([self.output, c_i], axis=-1)操作 ，这句话是不是将权重加权平均到原来的LSTM输出向量中了？





------------------ 原始邮件 ------------------
发件人: "Jn Hua"<notifications@github.com>;
发送时间: 2019年8月14日(星期三) 上午10:52
收件人: "JNhua/Chinese_NER_with_Attention"<Chinese_NER_with_Attention@noreply.github.com>;
抄送: "胸毛特长"<995958609@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [JNhua/Chinese_NER_with_Attention] 关于项目的论文 (#2)



 
您好 能告诉一下我这个项目的论文题目吗 我想学习一下
  
此为毕业设计论文，未发表
